EverGrandeCity_DevelopersHouse_MapScripts::
	.byte 0

EverGrandeCity_DevelopersHouse_EventScript_Man::
	msgbox EverGrandeCity_DevelopersHouse_Text_Man, MSGBOX_NPC
	end

@TODO: this text will likely require updating.
EverGrandeCity_DevelopersHouse_Text_Man:
	.string "Hey there, player! I hope you're having\n"
	.string "a good time with Energized Emerald.\p"
	.string "My aim with this romhack was to spice\n"
	.string "things up and make it fun and exciting,\l"
	.string "whilst also enhancing the character of\l"
	.string "the region.\p"
	.string "It may feel like you're approaching the\n"
	.string "endgame, but there is a load of cool\l"
	.string "new content after beating the Pokémon\l"
	.string "League.\p"
	.string "Have fun!$"
