Wildwoods_Area3_MapScripts::
	.byte 0

Wildwoods_Area3_Eventscript_MagmaM::
	msgbox Wildwoods_Area3_Text_LostGrunt, MSGBOX_NPC
	end

Wildwoods_Area3_Text_LostGrunt:
	.string "I'm completely lost.\n"
	.string "I can't find the others.\p"
	.string "My mom used to tell me stories of what\n"
	.string "happens to people who lose their way in\l"
	.string "the woods when I was a kid.\p"
	.string "I really hope those stories don't have\n"
	.string "any truth to them!$"
