EverGrandeCity_BattleTent_MapScripts::
	.byte 0

EverGrandeCity_BattleTent_EventScript_Teala::
	msgbox EverGrandeCity_BattleTent_Text_Teala, MSGBOX_NPC
	end

EverGrandeCity_BattleTent_EventScript_Beauty::
	end

EverGrandeCity_BattleTent_EventScript_BlackBelt::
	end

EverGrandeCity_BattleTent_EventScript_BugCatcher::
	end

EverGrandeCity_BattleTent_EventScript_Delinquent::
	msgbox EverGrandeCity_BattleTent_Text_Delinquent, MSGBOX_NPC
	end

EverGrandeCity_BattleTent_EventScript_ExpertF::
	end

EverGrandeCity_BattleTent_EventScript_ExpertM::
	end

EverGrandeCity_BattleTent_EventScript_FairyTaleGirl::
	end

EverGrandeCity_BattleTent_EventScript_Hiker::
	end

EverGrandeCity_BattleTent_EventScript_HexManiac::
	end

EverGrandeCity_BattleTent_EventScript_Guitarist::
	end

EverGrandeCity_BattleTent_EventScript_Maniac::
	end

EverGrandeCity_BattleTent_EventScript_CoolTrainerM::
	end

EverGrandeCity_BattleTent_EventScript_NinjaBoy::
	end

EverGrandeCity_BattleTent_EventScript_RangerF::
	end

EverGrandeCity_BattleTent_EventScript_RangerM::
	end

EverGrandeCity_BattleTent_EventScript_PsychicM::
	msgbox EverGrandeCity_BattleTent_Text_PsychicM, MSGBOX_NPC
	end

EverGrandeCity_BattleTent_EventScript_RichBoy::
	end

EverGrandeCity_BattleTent_EventScript_TriathleteF::
	end

EverGrandeCity_BattleTent_EventScript_TriathleteM::
	end

EverGrandeCity_BattleTent_EventScript_StreetThug::
	msgbox EverGrandeCity_BattleTent_Text_StreetThug, MSGBOX_NPC
	end

EverGrandeCity_BattleTent_EventScript_Lady::
	end

EverGrandeCity_BattleTent_EventScript_CoolTrainerF::
	end

EverGrandeCity_BattleTent_Text_Delinquent:
	.string "TODO"

EverGrandeCity_BattleTent_Text_StreetThug:
	.string "TODO"

EverGrandeCity_BattleTent_Text_PsychicM:
	.string "TODO"

EverGrandeCity_BattleTent_Text_Teala:
	.string "Hello, and welcome to the Battle Tent.\p"
	.string "Here trainers may come here to battle\n"
	.string "with other trainers.\p"
	.string "New trainers come in every day. You may\n"
	.string "check in daily for new battles.$"
