Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemQuickBall::
	finditem ITEM_QUICK_BALL
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemPokeBall::
	finditem ITEM_POKE_BALL
	end

Route104_EventScript_ItemXAccuracy::
	finditem ITEM_X_ACCURACY
	end

Route104_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route105_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route106_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route108_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route109_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route109_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route110_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route110_EventScript_ItemDireHit::
	finditem ITEM_DIRE_HIT
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route113_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSuperPotion::
	finditem ITEM_SUPER_POTION
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

Route115_EventScript_ItemIron::
	finditem ITEM_IRON
	end

Route115_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_REPEL
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route117_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

Route117_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

Route119_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route119_EventScript_ItemLeafStone::
	finditem ITEM_LEAF_STONE
	end

Route119_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route119_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemHyperPotion2::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_ELIXIR
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route121_EventScript_ItemShinyStone::
	finditem ITEM_SHINY_STONE
	end

Route123_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route123_EventScript_ItemRevivalHerb::
	finditem ITEM_REVIVAL_HERB
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

PetalburgCity_EventScript_ItemDawnStone::
	finditem ITEM_DAWN_STONE
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemXDefend::
	finditem ITEM_X_DEFENSE
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemBigRoot::
	finditem ITEM_BIG_ROOT
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

RusturfTunnel_EventScript_ItemTM63::
	finditem ITEM_TM63
	end

RusturfTunnel_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

GraniteCave_1F_EventScript_ItemTM69::
	finditem ITEM_TM69
	end

GraniteCave_B1F_EventScript_ItemDuskBall::
	finditem ITEM_DUSK_BALL
	end

GraniteCave_B1F_EventScript_ItemHardStone::
	finditem ITEM_HARD_STONE
	end

GraniteCave_B2F_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

JaggedPass_EventScript_ItemBurnHeal::
	finditem ITEM_BURN_HEAL
	end

FieryPath_EventScript_ItemGreatBall::
	finditem ITEM_GREAT_BALL
	end

FieryPath_EventScript_ItemFreshWater::
	finditem ITEM_FRESH_WATER
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_FIRE_STONE
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_PARALYZE_HEAL
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM79::
	finditem ITEM_TM79
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	finditem ITEM_LUXURY_BALL
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	finditem ITEM_WATER_STONE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

SafariZone_Northwest_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemTM81::
	finditem ITEM_TM81
	end

MtPyre_2F_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemDestinyKnot::
	finditem ITEM_DESTINY_KNOT
	end

MtPyre_5F_EventScript_ItemReaperCloth::
	finditem ITEM_REAPER_CLOTH
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

AquaHideout_B1F_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM71::
	finditem ITEM_TM71
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

VictoryRoad_B2F_EventScript_ItemProtector::
	finditem ITEM_PROTECTOR
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

MagmaHideout_2F_2R_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

MossdeepCity_StevensHouse_EventScript_ItemTM91::
	finditem ITEM_TM91
	end

LittlerootBeach_EventScript_ItemTM58::
	finditem ITEM_TM58
	end

LittlerootBeach_EventScript_ItemCalmMint::
	finditem ITEM_CALM_MINT
	end

Wildwoods_Area5_EventScript_ItemTimidMint::
	finditem ITEM_TIMID_MINT
	end

Wildwoods_Area7_EventScript_ItemTM99::
	finditem ITEM_TM99
	end

FallarborWasteland_EventScript_ItemTM67::
	finditem ITEM_TM67
	end

FallarborWasteland_EventScript_ItemImpishMint::
	finditem ITEM_IMPISH_MINT
	end

MauvilleMeadow_EventScript_ItemTM93::
	finditem ITEM_TM93
	end

MauvilleMeadow_EventScript_ItemBoldMint::
	finditem ITEM_BOLD_MINT
	end

FortreeJungle_Area2_EventScript_ItemTM09::
	finditem ITEM_TM09
	end

FortreeJungle_Area3_EventScript_ItemJollyMint::
	finditem ITEM_JOLLY_MINT
	end

CrumblingGorge_EventScript_ItemTM86::
	finditem ITEM_TM86
	end

CrumblingGorge_EventScript_ItemCarefulMint::
	finditem ITEM_CAREFUL_MINT
	end

NavelRock_Entrance_Eventscript_ItemEscapeRope::
	finditem ITEM_ESCAPE_ROPE
	end

NavelRock_Lugia1_Eventscript_ItemModestMint::
	finditem ITEM_MODEST_MINT
	end

NavelRock_Lugia2_Eventscript_ItemRareCandy::
	finditem ITEM_RARE_CANDY
	end

NavelRock_Lugia3_Eventscript_ItemTM60::
	finditem ITEM_TM60
	end

NavelRock_Hooh1_Eventscript_ItemAdamantMint::
	finditem ITEM_ADAMANT_MINT
	end

NavelRock_Hooh2_Eventscript_ItemTM97::
	finditem ITEM_TM97
	end

NavelRock_Hooh3_Eventscript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

NavelRock_Bottom_Eventscript_ItemSilverWing::
	finditem ITEM_SILVER_WING
	msgbox Text_FoundSilverWing, MSGBOX_DEFAULT
	closemessage
	end

NavelRock_Hooh3_Eventscript_ItemRainbowWing::
	finditem ITEM_RAINBOW_WING
	msgbox Text_FoundRainbowWing, MSGBOX_DEFAULT
	closemessage
	end

Text_FoundSilverWing:
	.string "You have found a legendary artifact!\n"
	.string "Kyogre should appear for you now.$"

Text_FoundRainbowWing:
	.string "You have found a legendary artifact!\n"
	.string "Groudon should appear for you now.$"

FarawayIsland_Ruin1_Eventscript_ItemHeartScale::
	finditem ITEM_HEART_SCALE
	end

FarawayIsland_Ruin2_Eventscript_ItemRareBone::
	finditem ITEM_RARE_BONE
	end

FarawayIsland_Ruin3_Eventscript_ItemLifeOrb::
	finditem ITEM_LIFE_ORB
	end

FarawayIsland_Ruin4_Eventscript_ItemLightClay::
	finditem ITEM_LIGHT_CLAY
	end

FarawayIsland_Ruin5_Eventscript_ItemTwistedSpoon::
	finditem ITEM_TWISTED_SPOON
	end

Mauville_Riverside_Eventscript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end
