OverworldPokemon_EventScript_Zigzagoon::
	locktarget
	faceplayer
	playmoncry SPECIES_ZIGZAGOON, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Poochyena::
	locktarget
	faceplayer
	playmoncry SPECIES_POOCHYENA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Pikachu::
	locktarget
	faceplayer
	playmoncry SPECIES_PIKACHU, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Skitty::
	locktarget
	faceplayer
	playmoncry SPECIES_SKITTY, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Wingull::
	locktarget
	faceplayer
	playmoncry SPECIES_WINGULL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Azurill::
	locktarget
	faceplayer
	playmoncry SPECIES_AZURILL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Azumarill::
	locktarget
	faceplayer
	playmoncry SPECIES_AZUMARILL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Kecleon::
	locktarget
	faceplayer
	playmoncry SPECIES_KECLEON, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Kirlia::
	locktarget
	faceplayer
	playmoncry SPECIES_KIRLIA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Dusclops::
	locktarget
	faceplayer
	playmoncry SPECIES_DUSCLOPS, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Linoone::
	locktarget
	faceplayer
	playmoncry SPECIES_LINOONE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Wurmple::
	locktarget
	faceplayer
	playmoncry SPECIES_WURMPLE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Beautifly::
	locktarget
	faceplayer
	playmoncry SPECIES_BEAUTIFLY, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Ludicolo::
	locktarget
	faceplayer
	playmoncry SPECIES_LUDICOLO, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Nuzleaf::
	locktarget
	faceplayer
	playmoncry SPECIES_NUZLEAF, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Taillow::
	locktarget
	faceplayer
	playmoncry SPECIES_TAILLOW, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Ralts::
	locktarget
	faceplayer
	playmoncry SPECIES_RALTS, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Shroomish::
	locktarget
	faceplayer
	playmoncry SPECIES_SHROOMISH, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Whismur::
	locktarget
	faceplayer
	playmoncry SPECIES_WHISMUR, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Abra::
	locktarget
	faceplayer
	playmoncry SPECIES_ABRA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Kadabra::
	locktarget
	faceplayer
	playmoncry SPECIES_KADABRA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Makuhita::
	locktarget
	faceplayer
	playmoncry SPECIES_MAKUHITA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Nosepass::
	locktarget
	faceplayer
	playmoncry SPECIES_NOSEPASS, 0
	waitmoncry
	@applymovement LOCALID_NOSEPASS, Common_Movement_FaceLeft
	applymovement VAR_LAST_TALKED, Common_Movement_FaceLeft
	waitmovement 0
	release
	end

OverworldPokemon_EventScript_Geodude::
	locktarget
	faceplayer
	playmoncry SPECIES_GEODUDE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Graveler::
	locktarget
	faceplayer
	playmoncry SPECIES_GRAVELER, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Delcatty::
	locktarget
	faceplayer
	playmoncry SPECIES_DELCATTY, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Mawile::
	locktarget
	faceplayer
	playmoncry SPECIES_MAWILE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Sableye::
	locktarget
	faceplayer
	playmoncry SPECIES_SABLEYE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Machop::
	locktarget
	faceplayer
	playmoncry SPECIES_MACHOP, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Machoke::
	locktarget
	playmoncry SPECIES_MACHOKE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Meditite::
	locktarget
	faceplayer
	playmoncry SPECIES_MEDITITE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Medicham::
	locktarget
	faceplayer
	playmoncry SPECIES_MEDICHAM, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Electrike::
	locktarget
	faceplayer
	playmoncry SPECIES_ELECTRIKE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Magnemite::
	locktarget
	faceplayer
	playmoncry SPECIES_MAGNEMITE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Phanpy::
	locktarget
	faceplayer
	playmoncry SPECIES_PHANPY, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Oddish::
	locktarget
	faceplayer
	playmoncry SPECIES_ODDISH, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Bellossom::
	locktarget
	faceplayer
	playmoncry SPECIES_BELLOSSOM, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Doduo::
	locktarget
	faceplayer
	playmoncry SPECIES_DODUO, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Roselia::
	locktarget
	faceplayer
	playmoncry SPECIES_ROSELIA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Numel::
	locktarget
	faceplayer
	playmoncry SPECIES_NUMEL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Koffing::
	locktarget
	faceplayer
	playmoncry SPECIES_KOFFING, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Sandshrew::
	locktarget
	faceplayer
	playmoncry SPECIES_SANDSHREW, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Spinda::
	locktarget
	faceplayer
	playmoncry SPECIES_SPINDA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Vibrava::
	locktarget
	faceplayer
	playmoncry SPECIES_VIBRAVA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Swablu::
	locktarget
	faceplayer
	playmoncry SPECIES_SWABLU, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Zangoose::
	locktarget
	faceplayer
	playmoncry SPECIES_ZANGOOSE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Baltoy::
	locktarget
	faceplayer
	playmoncry SPECIES_BALTOY, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Jigglypuff::
	locktarget
	faceplayer
	playmoncry SPECIES_JIGGLYPUFF, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Shuppet::
	locktarget
	faceplayer
	playmoncry SPECIES_SHUPPET, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Duskull::
	locktarget
	faceplayer
	playmoncry SPECIES_DUSKULL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Chimecho::
	locktarget
	faceplayer
	playmoncry SPECIES_CHIMECHO, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Vulpix::
	locktarget
	faceplayer
	playmoncry SPECIES_VULPIX, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Psyduck::
	locktarget
	faceplayer
	playmoncry SPECIES_PSYDUCK, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Wynaut::
	locktarget
	faceplayer
	playmoncry SPECIES_WYNAUT, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Natu::
	locktarget
	faceplayer
	playmoncry SPECIES_NATU, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Snorunt::
	locktarget
	faceplayer
	playmoncry SPECIES_SNORUNT, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Spheal::
	locktarget
	faceplayer
	playmoncry SPECIES_SPHEAL, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Corsola::
	locktarget
	faceplayer
	playmoncry SPECIES_CORSOLA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Chinchou::
	locktarget
	faceplayer
	playmoncry SPECIES_CHINCHOU, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Bagon::
	locktarget
	faceplayer
	playmoncry SPECIES_BAGON, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Beldum::
	locktarget
	faceplayer
	playmoncry SPECIES_BELDUM, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Castform::
	locktarget
	faceplayer
	playmoncry SPECIES_CASTFORM, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Eevee::
	locktarget
	faceplayer
	playmoncry SPECIES_EEVEE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Mightyena::
	locktarget
	faceplayer
	playmoncry SPECIES_MIGHTYENA, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Seedot::
	locktarget
	faceplayer
	playmoncry SPECIES_SEEDOT, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Nidoking::
	locktarget
	faceplayer
	playmoncry SPECIES_NIDOKING, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Scizor::
	locktarget
	faceplayer
	playmoncry SPECIES_SCIZOR, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Weavile::
	locktarget
	faceplayer
	playmoncry SPECIES_WEAVILE, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Magmortar::
	locktarget
	faceplayer
	playmoncry SPECIES_MAGMORTAR, 0
	waitmoncry
	release
	end

OverworldPokemon_EventScript_Gengar::
	locktarget
	faceplayer
	playmoncry SPECIES_GENGAR, 0
	waitmoncry
	release
	end
