FortreeJungle_Area2_MapScripts::
	.byte 0

FortreeJungle_Area2_Eventscript_AquaMember::
	msgbox FortreeJungle_Area2_Text_AquaMember, MSGBOX_NPC
	end

FortreeJungle_Area2_Text_AquaMember:
	.string "This place is so humid and prickly!\n"
	.string "I much prefer being out on the ocean.\p"
	.string "Perhaps I should take a dip in that\n"
	.string "pond? The Pokémon in there probably"
	.string "won't mind too much…$"
