Route119_House_MapScripts::
	.byte 0

Route119_House_EventScript_Woman::
	msgbox Route119_House_Text_RumorAboutCaveOfOrigin, MSGBOX_NPC
	end

Route119_House_Text_RumorAboutCaveOfOrigin:
	.string "There's a very rare fish Pokémon that\n"
	.string "can only be found in this river.\p"
	.string "They like to congregate in specific\n"
	.string "random patches of water.\p"
	.string "Though, sometimes those patches change.$"
