LavaridgeTown_House_MapScripts::
	.byte 0

LavaridgeTown_House_EventScript_OldMan::
	msgbox LavaridgeTown_House_Text_WifeWarmingEggInHotSprings, MSGBOX_NPC
	end

LavaridgeTown_House_Text_WifeWarmingEggInHotSprings:
	.string "My wife's warming an egg in the hot\n"
	.string "springs. This is what she told me.\p"
	.string "People can find eggs when they leave\n"
	.string "two Pokémon together at the daycare.$"
