EverGrandeCity_House1_MapScripts::
	.byte 0

EverGrandeCity_House1_EventScript_Woman::
	msgbox EverGrandeCity_House1_Text_Woman, MSGBOX_NPC
	end

EverGrandeCity_House1_Text_Woman:
	.string "For some reason, this island has a thick\n"
	.string "cover of flowers. I've always wondered\l"
	.string "why here of all places.\p"
	.string "Not that I'm complaining, the flowers\n"
	.string "are part the reason I moved here!$"
